### ISSUE TITLE
Process GROW NOM data

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/enviroMS#2]
Process GROW NOM data. 
Challenge is mapping ESS-DIVE to EMSL raw file.

**Comment by ssarrafan** [comment]
@corilo do you have any updates on this issue?  I am trying to close out the sprint on time since I'll be off next week.  Thanks for your help.

**Comment by ssarrafan** [comment]
Removing from sprint. @corilo please let me know if you plan to work on this in May.

**Comment by aclum** [comment]
I think this can be closed. NOM GROW data was processed for GSP 2023. @corilo  @mslarae13 please reopen if this is incorrect.
