### ISSUE TITLE
Preparation Metadata: NOM

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/enviroMS#4]
- [ ] microbiomedata/metaMS#13
- [ ] microbiomedata/metaMS#14
- [ ] microbiomedata/metaMS#15
- [ ] microbiomedata/enviroMS#3
- [ ] microbiomedata/metaMS#17

**Comment by ssarrafan** [comment]
@corilo @mslarae13 should this issue remain open and in the backlog?  Or can I close it?

**Comment by mslarae13** [comment]
I think we can close this issue in favor of the schema refactoring.
I'll look at the child issues and link them to the related issues from the refactor work
