### ISSUE TITLE
Modify metadata generation scripts for NOM workflow to berkeley-schema-fy24 

### ISSUE THREAD

**Issue by kheal** [microbiomedata/enviroMS#6]
Dependent on: 
https://github.com/microbiomedata/metaMS/issues/57

**Comment by kheal** [comment]
We will need to make change sheets for the existing metadata as well.  Related to https://github.com/microbiomedata/nmdc-schema/issues/1852 .

**Comment by ssarrafan** [comment]
@brynnz22 what's the status of this?

**Comment by brynnz22** [comment]
Hi Set. This is still being worked on, I tried to move it to the next sprint, but I can never find the next sprint listed, so I just removed. Its part of the Berkeley squad. So its there now.

**Comment by ssarrafan** [comment]
> Hi Set. This is still being worked on, I tried to move it to the next sprint, but I can never find the next sprint listed, so I just removed. Its part of the Berkeley squad. So its there now.
> 
> Just as an update:
> 
> * Biosample functionality is done
> * Mass Spectrometry functionality is done with the exception of the `has_calibration`

Thanks Brynn. I moved it to the new sprint. My suspicion is that when you look for the new sprint you are on the 'recent' tab and it won't come up there unless you've already looked at it. Try the organization tab and you should see all the sprints.  

<img width="240" alt="Screenshot 2024-08-26 at 9 01 27 AM" src="https://github.com/user-attachments/assets/31d48a57-d112-468c-9c8c-7d5d7e31ec56">

**Comment by mslarae13** [comment]
@kheal @brynnz22 new estimated completion date?

**Comment by brynnz22** [comment]
@mslarae13 I am thinking probably end of september, possibly sooner. Just want to give myself some wiggle room.

**Comment by brynnz22** [comment]
Update: Berkeley functionality is pretty much complete and updated for NOM with the exception of a few small details I need to check on with Yuri. The biggest thing left is adding calibration info for MasSpectrometery and/or NomAnalysis.

**Comment by ssarrafan** [comment]
@brynnz22 any update?  
since you mentioned needing till the end of Sept I'll move this to the next sprint

**Comment by brynnz22** [comment]
Sorry Set I am so bad about moving these ahead of time. Still working on it,  will hopefully be in Review by the end of next sprint.

**Comment by brynnz22** [comment]
Finished and in review.

**Comment by ssarrafan** [comment]
@brynnz22 are you expecting this review to be completed by Friday?

**Comment by brynnz22** [comment]
No. I will move to next sprint

**Comment by ssarrafan** [comment]
Since @brynnz22 is out today and tomorrow I will move this to the next sprint for review. Who should be reviewing this @brynnz22 ?

**Comment by brynnz22** [comment]
Thank you @ssarrafan for moving to the next spring, @corilo is reviewing it. I need to make changes he requested.
